sudo: required

language: go
go:
    - 1.5.1
    - 1.6.2

services:
    - docker

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
    # For integration with codecov.io
    - go get github.com/modocache/gover

    # reinstall docker-compose at specific version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose build

go_import_path: github.com/cfpb/rhobot

install:
    - go get github.com/Sirupsen/logrus
    - go get github.com/urfave/cli
    - go get -u github.com/davecgh/go-spew/spew
    - go get github.com/lib/pq
    - go get gopkg.in/yaml.v2
    - go get github.com/flosch/pongo2
    - go get gopkg.in/gomail.v2

script:
    # setup dockerized services
    - docker-compose up -d
    - sleep 300
    - docker ps
    - go test -v ./...
    - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
    - gover . coverprofile.txt

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverprofile.txt -v
